const assert = require('node:assert/strict');
const L = require('../logic.js');
const a={id:'a',sociability:8,reactivity:2,energy:7,playIntensity:6,tolerance:8,resourceSharing:7,vulnerability:2};
const b={id:'b',sociability:8,reactivity:2,energy:7,playIntensity:6,tolerance:8,resourceSharing:7,vulnerability:2};
const c={id:'c',sociability:2,reactivity:9,energy:10,playIntensity:10,tolerance:2,resourceSharing:2,vulnerability:1};
assert.equal(L.riskBand(0).level,'green');
assert.equal(L.riskBand(24).level,'green');
assert.equal(L.riskBand(25).level,'yellow');
assert.equal(L.riskBand(49).level,'yellow');
assert.equal(L.riskBand(50).level,'amber');
assert.equal(L.riskBand(74).level,'amber');
assert.equal(L.riskBand(75).level,'red');
assert.equal(L.riskBand(100).level,'red');
const low=L.interactionRisk(a,b,{capacity:30,population:3,groupEnergy:3,quiet:true,gateBusy:false,heatRisk:10});
assert(low.riskScore<=24,`expected low risk, got ${low.riskScore}`);
const high=L.interactionRisk(a,c,{capacity:8,population:12,groupEnergy:8,gateBusy:true,heatRisk:80});
assert(high.riskScore>=75,`expected red risk, got ${high.riskScore}`);
const cool=L.heatRisk({apparentTemperature:18,humidity:45,uvIndex:2,shadeAvailable:true,waterAvailable:true});
assert(cool.riskScore<=24,`expected green heat, got ${cool.riskScore}`);
const hot=L.heatRisk({apparentTemperature:39,humidity:80,uvIndex:11,directSun:true,shadeAvailable:false,waterAvailable:false,hotSurface:true,vulnerableDog:true});
assert(hot.riskScore>=75,`expected red heat, got ${hot.riskScore}`);
const puppyUnsafe=L.puppyAssessment({clearance:'none',setting:'busy-dog-park',mentor:'unknown-group'});
assert(puppyUnsafe.riskScore>=75,`expected red puppy plan, got ${puppyUnsafe.riskScore}`);
const puppyControlled=L.puppyAssessment({clearance:'public',setting:'puppy-class',mentor:'calm-adult'});
assert(puppyControlled.riskScore<=24,`expected green puppy plan, got ${puppyControlled.riskScore}`);
const stress=L.etiquetteRisk(['stiff','pinning','snapping']);
assert(stress.riskScore>=75,`expected red etiquette risk, got ${stress.riskScore}`);
const ready=L.departureRisk({lead:true,bags:true,water:true,idTag:true,vaccination:true,temperament:'calm'});
assert(ready.riskScore<=24,`expected green departure, got ${ready.riskScore}`);
const notReady=L.departureRisk({lead:false,bags:false,water:false,idTag:false,vaccination:false,temperament:'reactive'});
assert(notReady.riskScore>=75,`expected red departure, got ${notReady.riskScore}`);
console.log(JSON.stringify({ok:true,lowInteraction:low.riskScore,highInteraction:high.riskScore,coolHeat:cool.riskScore,hotHeat:hot.riskScore,puppyControlled:puppyControlled.riskScore,puppyUnsafe:puppyUnsafe.riskScore},null,2));
